name: Build Chrome Extension

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifact zip
        run: zip -r albz-ad-blocker.zip manifest.json background.js popup.html icon.png README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: albz-ad-blocker
          path: albz-ad-blocker.zip
