name: Build Chrome Extension

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Version is $VERSION"

      - name: Create artifact zip with version in name
        run: |
          zip -r adBlocker.zip manifest.json content.js background.js popup.html popup.js style.css icons/ README.md
          ls -l adBlocker.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: adBlocker-${{ steps.get_version.outputs.VERSION }}
          path: adBlocker.zip