name: Build Chrome Extension

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is $VERSION"

      - name: Create artifact zip with version in name
        run: |
          zip -r albz-ad-blocker-${VERSION}.zip manifest.json background.js popup.html icon.png README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: albz-ad-blocker-${VERSION}
          path: albz-ad-blocker-${VERSION}.zip
